plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.9'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.hsy'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
    //Thymeleaf 템플릿 엔진
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    // 기본 웹 MVC (@Controller, Rest API 등)
	implementation 'org.springframework.boot:spring-boot-starter-web'
    // 코드 변경시 자동 리스타트, 개발환경 전용
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
    // mysqlDB
	runtimeOnly 'com.mysql:mysql-connector-j'
    // Lombok Getter,Setter
    compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
    // Test JUnit5, AssertJ, Spring test...
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    // Security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    // JPA + Hibernate ... ORM
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // Thymeleaf base.html(공통 레이아웃)
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect'
    // 유효성 검사
    implementation 'org.springframework.boot:spring-boot-starter-validation'
}

tasks.named('test') {
	useJUnitPlatform()
}
